/* eslint-disable react/jsx-no-undef */
import Head from "next/head";
import styles from "../styles/Home.module.css";

import { GamePlan } from "../components/GamePlan";
import { CarouselFade } from "../components/CarouselFade";
import { Category } from "../components/Category";
import {
  Box,
  Flex,
  Grid,
  GridItem,
  StackDivider,
  VStack,
} from "@chakra-ui/react";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* carousel image */}
      <CarouselFade />
      <Grid
        templateAreas={`
                  "nav main"
                  "footer footer"`}
        gap="2"
        fontWeight="bold"
        gridTemplateColumns={'300px 1fr'}
      >
        {/* navigation */}
        <GridItem pl="2" bg="pink.300"area={"nav"}>
          <Category />
        </GridItem>

        {/* main content */}
        <GridItem pl="2" bg="green.300" area={"main"}>
          <Flex align="center" justify="center" wrap="wrap">
            <GamePlan />
            <GamePlan />
            <GamePlan />
            <GamePlan />
            <GamePlan />
            <GamePlan />
            <GamePlan />
            <GamePlan />
            <GamePlan />
            <GamePlan />
            <GamePlan />
            <GamePlan />
            <GamePlan />
            <GamePlan />
            <GamePlan />
            <GamePlan />
            <GamePlan />
            <GamePlan />
            <GamePlan />
          </Flex>
        </GridItem>

        {/* footer */}
        <GridItem pl="2" bg="blue.300" area={"footer"}>
          Footer
        </GridItem>
      </Grid>
    </div>
  );
}
