/* eslint-disable react/jsx-no-undef */
import Head from "next/head";
import { GamePlan } from "../components/GamePlan";
import { CarouselFade } from "../components/CarouselFade";
import { CategorySearch } from "../components/CategorySearch";
import {
  Box,
  Flex,
  Grid,
  GridItem,
  StackDivider,
  VStack,
} from "@chakra-ui/react";
import { SearchIcon } from "@chakra-ui/icons";
import { planCollectionAtom } from "../components/atoms/planCollectionAtom";
import { useRecoilValue, useSetRecoilState } from "recoil";
import { showGamePlanAtom } from "../components/atoms/showGamePlanAtom";
import React from "react";
import { Route } from "react-router-dom";

const Home = () => {
  const setShowGamePlan = useSetRecoilState(showGamePlanAtom);
  const planCollections = useRecoilValue(planCollectionAtom);
  setShowGamePlan(planCollections);

  return (
    <Box>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* carousel image */}
      <CarouselFade />

      {/* mainContents */}
      <Grid
        templateAreas={`
        "nav main"
        "footer footer"`}
        gap="2"
        fontWeight="bold"
        gridTemplateColumns={"300px 1fr"}
        mt="3"
      >
        {/* search category */}
        <GridItem
          area={"nav"}
          bg="whiteAlpha.800"
          borderRadius="10"
          ml="10"
          p="2"
        >
          <VStack
            divider={<StackDivider borderColor="purple.300" />}
            spacing={4}
            align="stretch"
          >
            <Box h="40px">
              <span style={{ marginLeft: 10 }}>
                <SearchIcon />
                <span>カテゴリ</span>
              </span>
            </Box>
            <CategorySearch category="FPS・TPS" />
            <CategorySearch category="MOBA" />
            <CategorySearch category="格闘" />
            <CategorySearch category="スポーツ" />
            <CategorySearch category="エーペックスレジェンズ" />
          </VStack>
        </GridItem>

        {/* show plan */}
        <GridItem pl="2" area={"main"} ml="1">
          <Flex
            align="center"
            wrap="wrap"
            bg="whiteAlpha.800"
            maxW="1000px"
            borderRadius="10"
          >
              <GamePlan />
          </Flex>
        </GridItem>
      </Grid>
    </Box>
  );
};
export default Home;
